name: belajar_dart
description: Latihan Dart Programming Language.
version: 1.0.0
# homepage: tuflihun.site

environment:
  sdk: ">=2.15.1 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
